### ISSUE TITLE
Can this package be used to process data from spikegadgets online?

### ISSUE THREAD

**Issue by Dililianxice** [LiuLab-Bioelectronics-Harvard/AutoSort#1]
As the title. This is a good package for handling Intan data. But I want to use it for processing spikegadgets data(.rec).

**Comment by arnaumarin** [comment]
Hi there! Thanks for opening this issue.

I'm not personally familiar with SpikeGadgets, but if you can load its data into SpikeInterface (https://spikeinterface.readthedocs.io/en/stable/), you should be able to process it offline without any issues. If you run into any difficulties with this setup, please share more details, and we’ll do our best to help.

For real-time processing, your approach will depend on the hardware you’re using. For example, with Intan, reading raw recordings in real-time is straightforward. If SpikeGadgets provides a way to access raw channel data in real-time or outputs files that can be quickly read by Python, real-time analysis should be feasible. Keep in mind that running AutoSort effectively requires defining the probe geometry you’re using, both during training and inference.

Feel free to share more details about your current setup so we can better guide you!

**Comment by Dililianxice** [comment]
> n

Thank u for your help! I will try!
